// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAS8Tpm6CRQE7h-0-qHIbg04OpO1VcqZg',
    appId: '1:193106600716:web:2a45333498c5d6846c1f29',
    messagingSenderId: '193106600716',
    projectId: 'app12-c563a',
    authDomain: 'app12-c563a.firebaseapp.com',
    databaseURL: 'https://app12-c563a-default-rtdb.firebaseio.com',
    storageBucket: 'app12-c563a.firebasestorage.app',
    measurementId: 'G-TMCBMWFN9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLbFu5zVi3eFhu4PBbYXKrYtY61fOUrAg',
    appId: '1:193106600716:android:fbe8a2bc5fec586f6c1f29',
    messagingSenderId: '193106600716',
    projectId: 'app12-c563a',
    databaseURL: 'https://app12-c563a-default-rtdb.firebaseio.com',
    storageBucket: 'app12-c563a.firebasestorage.app',
  );
}
